deploy-job:      
  stage: deploy  
  tags:
    - "inventory-management-new"
  variables:
    BUILD_DIR: "/var/www/html/builds/gWp6HqgB/0/dhruvanshu.p/imanagement/"
    TARGET_DIR: "/var/www/html/inventory-management"
  script:
    - echo "Deploying application..."
    #- rsync -P -av $BUILD_DIR/* $TARGET_DIR
    - cd $TARGET_DIR
    - pip3 install -r requirements.txt
    - echo "Application successfully deployed."
    - rm -rf /home/admin/gWp6HqgB/
  only:
    - master
